; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini

[color]
bg = #0d110f
fg = #e2e8f0
mb = #18241d

pacmanA="#719e74"
pacmanB="#5a7d60"

red = #e06c75
pink = #c678dd
purple = #b48ead
blue = #61afef
blue-arch = #4ba3e3
cyan = #56b6c2
teal = #56b6c2
green = #5dbb63     
lime = #79c07b
yellow = #d19a66
amber = #e5c07b
orange = #d19a66
brown = #986801
grey = #5c6370
indigo = #61afef
blue-gray = #5c6370
white = #e2e8f0

[bar/emi-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = false

width = 88%
height = 23

offset-x = 2%
offset-y = 6

background = ${color.bg}
foreground = ${color.fg}

radius = 2

line-size = 2
line-color = ${color.blue}

border-size = 8px
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=9;3"
; font-0 = "Cozette:pixelsize=16;4"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=15;4"
; Glyphs
font-4 = "MesloLGS NF:style=Regular:pixelsize=17;4"
;dpi = 96
font-5 = "DejaVu Sans:style=Regular:size=10;3"
font-6 = "Noto Sans:style=Regular:size=10;3"
font-7 = "JetBrainsMono:style=Bold:pixelsize=9;3"

;Modules availables but not active:
;		brightness		weather		xkeyboard
modules-left = bi bspwm bd dots bi cpu_bar msep memory_bar msep filesystem msep filesystem_data bd sep sep nightlight sep colorpicker
modules-center = bi mpris_multi bd
# bi updates bd
modules-right = mpd sep bluetooth sep bi battery network bd sep bi pulseaudio bd sep bi date bd sep tray sep power

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
